[package]
name = "day-6_custom-customs"
version = "0.1.0"
authors = ["wannestas <taswannes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
